#!/bin/bash


do_deploy() {
	SRC_DIR=/build/tmp/$2/$3-glibc/deploy/$1
	DEPLOY_DIR=/chirpstack-gateway-os/deploy/$2/$3/$1

	mkdir -p $DEPLOY_DIR

	find $SRC_DIR/images -type f -name "*.wic.gz" -exec cp {} $DEPLOY_DIR \;
	find $SRC_DIR/images -type f -name "*.swu" -exec cp {} $DEPLOY_DIR \;
	cp -R $SRC_DIR/licenses $DEPLOY_DIR
}


VERSION="3.3.0-test.3"

do_deploy $VERSION "raspberrypi" "raspberrypi3"
do_deploy $VERSION "raspberrypi" "raspberrypi"
