diff --git a/Makefile b/Makefile
index 1891c3a4ac..4c7ac12391 100644
--- a/Makefile
+++ b/Makefile
@@ -3,7 +3,7 @@
 VERSION = 2018
 PATCHLEVEL = 09
 SUBLEVEL =
-EXTRAVERSION =
+EXTRAVERSION = -wifx
 NAME =
 
 # *DOCUMENTATION*
